### ISSUE TITLE
Compatibility with 1.20.1 ?

### ISSUE THREAD

**Issue by tt-thoma** [SamB440/AnvilLogin#1]
Recenlty, I got your plugin installed on my 1.20.1 Paper server, but I cannot make the plugin run because it's said "incompatible".

Trace Log:
```
[19:41:28 WARN]: [AnvilLogin] Task #29 for AnvilLogin v1.4 generated an exception
java.lang.ExceptionInInitializerError: null
	at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:476) ~[AnvilLogin-1.4.jar:?]
	at io.github.portlek.anvillogin.AnvilLogin.lambda$openRegister$3(AnvilLogin.java:74) ~[AnvilLogin-1.4.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.jar:git-Paper-17]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.jar:git-Paper-17]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.RuntimeException: Your server version isn't supported in AnvilGUI!
	at net.wesjd.anvilgui.version.VersionMatcher.lambda$match$1(VersionMatcher.java:52) ~[AnvilLogin-1.4.jar:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at net.wesjd.anvilgui.version.VersionMatcher.match(VersionMatcher.java:52) ~[AnvilLogin-1.4.jar:?]
	at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[AnvilLogin-1.4.jar:?]
	... 10 more
```

`Your server version isn't supported in AnvilGUI!`
Could you release a compatible version ?

**Comment by tt-thoma** [comment]
Well, nevermind
